import React, { createContext, useContext, useEffect, useState } from "react";

const translations = {
  en: {
    dir: "ltr",
    nav_findDoctor: "Find a doctor",
    nav_pharmacies: "Pharmacies",
    nav_ai: "AI Assistant",
    nav_login: "Log in",
    nav_getStarted: "Get started",
    nav_logout: "Log out",
    nav_dashboard: "My dashboard",
    nav_admin: "Admin",
    bottom_home: "Home",
    bottom_search: "Search",
    bottom_ai: "AI",
    bottom_profile: "Profile",
    home_badge: "Care that meets you where you are",
    home_title: "One app for doctors, labs, pharmacies, and honest guidance.",
    home_subtitle:
      "Search verified doctors, book in minutes, consult by video or text, order medicine from your prescription, and get a second opinion from our AI triage assistant.",
    home_searchPlaceholder: "Search specialty, e.g. Cardiology",
    home_search: "Search",
    home_cta_title: "Not sure where to start?",
    home_cta_desc: "Describe your symptoms to our AI assistant for preliminary guidance and a specialty recommendation.",
    home_cta_button: "Ask the AI assistant",
    login_title: "Welcome back",
    login_subtitle: "Log in to manage your appointments and prescriptions.",
    login_button: "Log in",
    login_noAccount: "No account?",
    login_create: "Create one",
    register_title: "Create your account",
    register_subtitle: "Join as a patient, doctor, lab, or pharmacy.",
    register_button: "Create account",
    register_haveAccount: "Already have an account?",
    footer_notice: "Not a substitute for professional medical advice. In an emergency, call your local emergency number.",

    // Profile / Care Hub menu
    profile_careHub: "Care Hub",
    profile_viewAll: "View all your records",
    nav_invoices: "Invoices",
    nav_invoices_desc: "Payments & billing history",
    nav_radiology: "Radiology",
    nav_radiology_desc: "Scans & imaging reports",
    nav_healthStatus: "Health Status",
    nav_healthStatus_desc: "Vitals & overall wellbeing",
    nav_admissions: "Admission Permits",
    nav_admissions_desc: "Entry, exit & case details",
    nav_labTests: "Lab Tests",
    nav_labTests_desc: "Test requests & results",
    nav_myAccount: "My account",
    nav_settings: "Settings",

    // Shared page chrome
    page_back: "Back",
    page_loading: "Loading your records...",
    page_refresh: "Refresh",
    page_download: "Download",
    page_search: "Search",
    page_filterAll: "All",
    page_noResults: "No matching records",

    // Invoices
    invoices_title: "Invoices",
    invoices_subtitle: "Your payments and billing history in one place.",
    invoices_totalPaid: "Total paid",
    invoices_pending: "Pending",
    invoices_totalInvoices: "Total invoices",
    invoices_empty_title: "No invoices yet",
    invoices_empty_desc: "Charges from consultations, labs, and pharmacy orders will show up here.",
    invoices_status_paid: "Paid",
    invoices_status_pending: "Pending",
    invoices_status_failed: "Failed",
    invoices_status_refunded: "Refunded",
    invoices_reference: "Reference",
    invoices_method: "Method",

    // Radiology
    radiology_title: "Radiology",
    radiology_subtitle: "Imaging scans, reports, and radiologist findings.",
    radiology_empty_title: "No scans on file",
    radiology_empty_desc: "X-rays, MRIs, CT scans, and ultrasounds ordered by your doctor will appear here.",
    radiology_status_scheduled: "Scheduled",
    radiology_status_inprogress: "In progress",
    radiology_status_completed: "Completed",
    radiology_status_cancelled: "Cancelled",
    radiology_findings: "Findings",
    radiology_radiologist: "Radiologist",
    radiology_urgent: "Urgent",
    radiology_routine: "Routine",

    // Health Status
    health_title: "Health Status",
    health_subtitle: "A snapshot of your vitals and overall wellbeing.",
    health_overall: "Overall status",
    health_bloodPressure: "Blood pressure",
    health_heartRate: "Heart rate",
    health_glucose: "Glucose level",
    health_oxygen: "Oxygen saturation",
    health_bloodType: "Blood type",
    health_height: "Height",
    health_weight: "Weight",
    health_allergies: "Allergies",
    health_conditions: "Chronic conditions",
    health_medications: "Current medications",
    health_doctorNotes: "Doctor's notes",
    health_lastCheckup: "Last checkup",
    health_empty_title: "No health record yet",
    health_empty_desc: "Once your doctor records your vitals, your health status will appear here.",
    health_status_excellent: "Excellent",
    health_status_good: "Good",
    health_status_fair: "Fair",
    health_status_needsattention: "Needs attention",
    health_status_critical: "Critical",
    health_none: "None recorded",

    // Admission permits
    admissions_title: "Admission Permits",
    admissions_subtitle: "Entry & exit permits with your case details.",
    admissions_empty_title: "No admission records",
    admissions_empty_desc: "Hospital entry and exit permits will be listed here once issued by a facility.",
    admissions_entry: "Entry permit",
    admissions_exit: "Exit permit",
    admissions_status_scheduled: "Scheduled",
    admissions_status_admitted: "Admitted",
    admissions_status_discharged: "Discharged",
    admissions_status_cancelled: "Cancelled",
    admissions_facility: "Facility",
    admissions_department: "Department",
    admissions_room: "Room",
    admissions_reason: "Reason",
    admissions_diagnosis: "Diagnosis",
    admissions_caseDetails: "Case details",
    admissions_admissionDate: "Admission date",
    admissions_dischargeDate: "Discharge date",

    // Lab tests
    labs_title: "Lab Tests",
    labs_subtitle: "Track every test request from sample to result.",
    labs_tab_all: "All",
    labs_tab_requested: "Requested",
    labs_tab_processing: "Processing",
    labs_tab_completed: "Completed",
    labs_searchPlaceholder: "Search a test name or lab...",
    labs_empty_title: "No lab tests yet",
    labs_empty_desc: "Tests requested by you or your doctor will show up here with live status.",
    labs_status_requested: "Requested",
    labs_status_processing: "Processing",
    labs_status_completed: "Completed",
    labs_normalRange: "Normal range",
    labs_interpretation: "Interpretation",
    labs_viewReport: "View report",
    labs_requestNew: "Request a test",

    // Search doctors
    search_title: "Find a doctor",
    search_subtitle: "Filter by specialty, city, and rating.",
    search_specialtyPlaceholder: "Specialty (e.g. Cardiology)",
    search_cityPlaceholder: "City",
    search_anyRating: "Any rating",
    search_sortBy: "Sort by",
    search_sort_rating: "Top rated",
    search_sort_priceAsc: "Price: low to high",
    search_sort_priceDesc: "Price: high to low",
    search_sort_reviews: "Most reviewed",
    search_clearFilters: "Clear filters",
    search_resultsCount: "{count} doctors found",
    search_loading: "Finding the best doctors for you...",
    search_empty_title: "No doctors match your filters",
    search_empty_desc: "Try a different specialty, city, or clear your filters to see everyone.",
    search_error: "Could not load doctors. Is the backend running?",
    search_popularSpecialties: "Popular specialties",
    doctor_book: "Book",
    doctor_verified: "Verified",

    // Doctor profile / booking
    doctor_back: "Back to search",
    doctor_save: "Save",
    doctor_saved: "Saved",
    doctor_share: "Share",
    doctor_linkCopied: "Profile link copied!",
    doctor_perSession: "EGP per session",
    doctor_avgSession: "Average session",
    doctor_happyPatients: "Happy patients",
    doctor_about: "About",
    doctor_aboutFallback: "Dr. {name} is a highly qualified {specialty} specialist with years of experience in patient care. Dedicated to providing top-quality healthcare services.",
    doctor_qualifications: "Qualifications & Experience",
    doctor_qualificationsFallback: "MD, Specialized in {specialty}",
    doctor_clinics: "Clinic Locations",
    doctor_bookTitle: "Book a Consultation",
    doctor_typeLabel: "Type",
    doctor_type_video: "Video call",
    doctor_type_video_desc: "Face-to-face on video",
    doctor_type_audio: "Phone call",
    doctor_type_audio_desc: "Voice only",
    doctor_type_text: "Chat",
    doctor_type_text_desc: "Text messages",
    doctor_dateLabel: "Date & time",
    doctor_pickManually: "Pick manually",
    doctor_nextAvailable: "Next available slots",
    doctor_noSlots: "This doctor hasn't listed available slots yet — pick a time manually and they'll confirm it.",
    doctor_notesLabel: "Notes (optional)",
    doctor_notesPlaceholder: "Describe your symptoms or concerns...",
    doctor_submit: "Book appointment",
    doctor_submitting: "Booking...",
    doctor_pastDateError: "Please choose a date and time in the future.",
    doctor_noDateError: "Please select a date and time.",
    doctor_bookedTitle: "Appointment requested!",
    doctor_bookedDesc: "You'll get a confirmation once the doctor accepts.",
    doctor_viewDashboard: "View in my dashboard",
    doctor_infoEmail: "You'll receive a confirmation email with the meeting link.",
    doctor_trustSecure: "Secure & encrypted consultations",
    doctor_trustCancel: "Cancellation up to 24 hours before",
    doctor_notFound: "We couldn't find this doctor.",

    // Patient dashboard
    dash_welcome: "Welcome back",
    dash_subtitle: "Manage your appointments and health records",
    dash_bookAppt: "Book Appointment",
    dash_upcomingAppts: "Upcoming Appointments",
    dash_activePresc: "Active Prescriptions",
    dash_completedVisits: "Completed Visits",
    dash_tabAppointments: "Appointments",
    dash_tabPrescriptions: "Prescriptions",
    dash_loading: "Loading...",
    dash_noAppts_title: "No appointments yet",
    dash_noAppts_desc: "Book your first consultation with a doctor",
    dash_browseDoctors: "Browse Doctors",
    dash_joinCall: "Join Call",
    dash_leaveReview: "Leave Review",
    dash_waitingConfirm: "Waiting for doctor to confirm",
    dash_cancelAppt: "Cancel appointment",
    dash_cancelConfirm: "Cancel this appointment? This can't be undone.",
    dash_cancelling: "Cancelling...",
    dash_noPresc_title: "No prescriptions yet",
    dash_noPresc_desc: "Your prescriptions will appear after doctor consultations",
    dash_prescribedOn: "Prescribed on",
    dash_active: "Active",
    dash_noMedicines: "No medicines listed",
    dash_doctorNotes: "Doctor's notes",
    dash_orderMedicine: "Order Medicine",
    dash_download: "Download",
    status_pending: "Pending",
    status_confirmed: "Confirmed",
    status_completed: "Completed",
    status_cancelled: "Cancelled",
    consult_video: "Video consultation",
    consult_audio: "Phone consultation",
    consult_text: "Chat consultation",

    // Home — hero
    home_heroTitle1: "Quality Care,",
    home_heroTitle2: "Anytime Anywhere",
    home_heroDesc: "Connect with certified doctors, get expert advice and take control of your health from the comfort of your home.",
    home_heroBookBtn: "Book an Appointment",
    home_heroHowBtn: "How it Works",
    home_heroEmergencyBtn: "Emergency? Find help now",
    home_stat1Label: "Happy Patients",
    home_stat2Label: "Expert Doctors",
    home_stat3Label: "Satisfaction Rate",
    home_heroCardTitle: "Video Consultation",
    home_heroCardSub: "Available 24/7",
    home_heroCardReviews: "4.9/5 (1.2K+ reviews)",

    // Home — services
    home_servicesTitle: "Comprehensive Healthcare Solutions for You",
    home_servicesSubtitle: "Everything you need to stay healthy, all in one place",
    service_video_title: "Video Consultation",
    service_video_desc: "Talk to a doctor face-to-face",
    service_pharmacy_title: "Online Pharmacy",
    service_pharmacy_desc: "Medicines delivered to your door",
    service_labs_title: "Lab Tests",
    service_labs_desc: "Book & track test results",
    service_checkup_title: "Health Checkups",
    service_checkup_desc: "Preventive care packages",
    service_specialists_title: "Specialist Doctors",
    service_specialists_desc: "Find experts by specialty",
    service_247_title: "24/7 Availability",
    service_247_desc: "Schedule at your convenience",
    service_secure_title: "Secure & Private",
    service_secure_desc: "Your health data is protected",
    service_records_title: "Health Records",
    service_records_desc: "All your medical history in one place",
    home_exploreAll: "Explore All Services",

    // Home — how it works
    home_stepsTitle: "Simple Steps to Better Health",
    step_account_title: "Create Account",
    step_account_desc: "Sign up in minutes and complete your profile",
    step_choose_title: "Choose Service",
    step_choose_desc: "Select the service or doctor you need",
    step_connect_title: "Connect with Doctor",
    step_connect_desc: "Consult with a verified medical professional",
    step_better_title: "Get Better",
    step_better_desc: "Follow advice and stay healthy",
    home_getStarted: "Get Started Now",

    // Home — pricing
    home_pricingTitle: "Affordable Plans for Everyone",
    home_pricingSubtitle: "Choose the plan that works best for you",
    plan_basic_name: "Basic",
    plan_premium_name: "Premium",
    plan_family_name: "Family",
    plan_popular: "POPULAR",
    plan_perMonth: "/month",
    plan_choose: "Choose Plan",
    plan_basic_f1: "5 consultations/month",
    plan_basic_f2: "Chat support",
    plan_basic_f3: "Basic health records",
    plan_premium_f1: "Unlimited consultations",
    plan_premium_f2: "Priority support",
    plan_premium_f3: "Full health records",
    plan_premium_f4: "10% pharmacy discount",
    plan_family_f1: "Family coverage",
    plan_family_f2: "Priority support",
    plan_family_f3: "Full health records",
    plan_family_f4: "20% pharmacy discount",

    // Home — why choose us
    home_whyTitle: "Why Choose Wellpoint?",
    home_whySubtitle: "Your Health, Our Priority",
    benefit_experts_title: "Expert Doctors",
    benefit_experts_desc: "Certified & experienced professionals",
    benefit_secure_title: "Secure & Private",
    benefit_secure_desc: "Your data stays safe and encrypted",
    benefit_247_title: "24/7 Availability",
    benefit_247_desc: "Consult anytime, anywhere, any day",
    benefit_afford_title: "Affordable Pricing",
    benefit_afford_desc: "Quality care at reasonable rates",

    // Home — doctors
    home_doctorsTitle: "Meet Our Specialist Doctors",
    home_viewAllDoctors: "View All Doctors",
    home_bookNow: "Book Now",
    home_noDoctorsYet: "Doctors will appear here once they join the platform.",

    // Home — testimonials
    home_testimonialsTitle: "What Our Patients Say",
    testimonial1_text: "Amazing experience! Got a consultation from a doctor from home. Highly recommended!",
    testimonial2_text: "Professional and efficient service. The doctor really listened and gave great advice.",
    testimonial3_text: "Quick response time and very professional. Saved me time and money!",

    // Home — CTA
    home_ctaTitle: "Take the First Step Towards Better Health",
    home_ctaDesc: "Book an appointment with one of our expert doctors today.",
    home_ctaBtn: "Book Appointment",

    // Emergency
    emergency_navLabel: "Emergency",
    emergency_title: "Emergency Help",
    emergency_subtitle: "Share your location to find the nearest hospital and doctors, with directions.",
    emergency_locate_cta: "Use my location",
    emergency_locating: "Getting your location...",
    emergency_searchingHospitals: "Searching nearby hospitals...",
    emergency_searchingDoctors: "Finding nearby doctors...",
    emergency_routing: "Calculating the route...",
    emergency_deniedTitle: "Location access needed",
    emergency_deniedDesc: "Please allow location access in your browser to find the nearest help.",
    emergency_retry: "Try again",
    emergency_nearestHospital: "Nearest hospital",
    emergency_otherHospitals: "Other nearby hospitals",
    emergency_nearestDoctors: "Nearest doctors",
    emergency_distanceAway: "{distance} km away",
    emergency_etaDriving: "~{minutes} min by car",
    emergency_noHospitals: "No hospitals found nearby. Try widening your search or check your connection.",
    emergency_noDoctors: "No registered doctors near you yet.",
    emergency_callHospital: "Call hospital",
    emergency_getDirections: "Open in Maps",
    emergency_viewProfile: "View profile",
    emergency_yourLocation: "Your location",
    emergency_disclaimer: "In a life-threatening emergency, call your local emergency number immediately. This tool helps you find nearby care faster — it does not replace emergency services.",
    emergency_mapUnavailable: "The map couldn't be loaded. Check your internet connection.",
  },
  ar: {
    dir: "rtl",
    nav_findDoctor: "دكاترة",
    nav_pharmacies: "صيدليات",
    nav_ai: "المساعد الذكي",
    nav_login: "تسجيل الدخول",
    nav_getStarted: "ابدأ الآن",
    nav_logout: "تسجيل الخروج",
    nav_dashboard: "حسابي",
    nav_admin: "لوحة التحكم",
    bottom_home: "الرئيسية",
    bottom_search: "بحث",
    bottom_ai: "الذكاء الاصطناعي",
    bottom_profile: "حسابي",
    home_badge: "رعاية صحية أينما كنت",
    home_title: "تطبيق واحد للدكاترة، المعامل، الصيدليات، وإرشاد موثوق.",
    home_subtitle:
      "ابحث عن دكاترة موثقين، احجز في دقائق، استشر بالفيديو أو الشات، اطلب دواءك من الروشتة، واستشير مساعدنا الذكي.",
    home_searchPlaceholder: "ابحث عن تخصص، مثلاً قلب وأوعية دموية",
    home_search: "بحث",
    home_cta_title: "مش عارف تبدأ منين؟",
    home_cta_desc: "احكي لمساعدنا الذكي عن أعراضك عشان يوجهك للتخصص المناسب.",
    home_cta_button: "اسأل المساعد الذكي",
    login_title: "أهلاً بعودتك",
    login_subtitle: "سجّل دخولك لإدارة مواعيدك وروشتاتك.",
    login_button: "تسجيل الدخول",
    login_noAccount: "معندكش حساب؟",
    login_create: "أنشئ واحد",
    register_title: "أنشئ حسابك",
    register_subtitle: "انضم كمريض، دكتور، معمل، أو صيدلية.",
    register_button: "إنشاء الحساب",
    register_haveAccount: "عندك حساب بالفعل؟",
    footer_notice: "التطبيق لا يغني عن استشارة طبية متخصصة. في حالات الطوارئ اتصل برقم الطوارئ المحلي.",

    // Profile / Care Hub menu
    profile_careHub: "مركز رعايتي",
    profile_viewAll: "شوف كل سجلاتك",
    nav_invoices: "الفواتير",
    nav_invoices_desc: "المدفوعات وسجل الفواتير",
    nav_radiology: "الأشعة",
    nav_radiology_desc: "صور الأشعة وتقاريرها",
    nav_healthStatus: "الحالة الصحية",
    nav_healthStatus_desc: "المؤشرات الحيوية والحالة العامة",
    nav_admissions: "تصاريح الدخول والخروج",
    nav_admissions_desc: "تصاريح الدخول والخروج وتفاصيل الحالة",
    nav_labTests: "التحاليل",
    nav_labTests_desc: "طلبات ونتائج التحاليل",
    nav_myAccount: "حسابي",
    nav_settings: "الإعدادات",

    // Shared page chrome
    page_back: "رجوع",
    page_loading: "بنجهز سجلاتك...",
    page_refresh: "تحديث",
    page_download: "تحميل",
    page_search: "بحث",
    page_filterAll: "الكل",
    page_noResults: "مفيش نتائج مطابقة",

    // Invoices
    invoices_title: "الفواتير",
    invoices_subtitle: "كل مدفوعاتك وفواتيرك في مكان واحد.",
    invoices_totalPaid: "إجمالي المدفوع",
    invoices_pending: "قيد الانتظار",
    invoices_totalInvoices: "عدد الفواتير",
    invoices_empty_title: "لسه مفيش فواتير",
    invoices_empty_desc: "هتظهر هنا فواتير الاستشارات والتحاليل وطلبات الصيدلية.",
    invoices_status_paid: "مدفوعة",
    invoices_status_pending: "قيد الانتظار",
    invoices_status_failed: "فشلت",
    invoices_status_refunded: "مسترجعة",
    invoices_reference: "الرقم المرجعي",
    invoices_method: "طريقة الدفع",

    // Radiology
    radiology_title: "الأشعة",
    radiology_subtitle: "صور الأشعة والتقارير وملاحظات الأخصائي.",
    radiology_empty_title: "لسه مفيش أشعة مسجلة",
    radiology_empty_desc: "أي أشعة سينية أو رنين أو مقطعية أو سونار يطلبها دكتورك هتظهر هنا.",
    radiology_status_scheduled: "معاد محدد",
    radiology_status_inprogress: "جاري التنفيذ",
    radiology_status_completed: "مكتملة",
    radiology_status_cancelled: "ملغاة",
    radiology_findings: "النتائج",
    radiology_radiologist: "أخصائي الأشعة",
    radiology_urgent: "عاجل",
    radiology_routine: "روتيني",

    // Health Status
    health_title: "الحالة الصحية",
    health_subtitle: "لمحة سريعة عن مؤشراتك الحيوية وحالتك العامة.",
    health_overall: "الحالة العامة",
    health_bloodPressure: "ضغط الدم",
    health_heartRate: "معدل ضربات القلب",
    health_glucose: "نسبة السكر",
    health_oxygen: "نسبة الأكسجين",
    health_bloodType: "فصيلة الدم",
    health_height: "الطول",
    health_weight: "الوزن",
    health_allergies: "الحساسية",
    health_conditions: "الأمراض المزمنة",
    health_medications: "الأدوية الحالية",
    health_doctorNotes: "ملاحظات الدكتور",
    health_lastCheckup: "آخر كشف",
    health_empty_title: "لسه مفيش سجل صحي",
    health_empty_desc: "لما دكتورك يسجل مؤشراتك الحيوية، هتظهر حالتك الصحية هنا.",
    health_status_excellent: "ممتازة",
    health_status_good: "جيدة",
    health_status_fair: "متوسطة",
    health_status_needsattention: "محتاجة متابعة",
    health_status_critical: "حرجة",
    health_none: "مفيش بيانات مسجلة",

    // Admission permits
    admissions_title: "تصاريح الدخول والخروج",
    admissions_subtitle: "تصاريح الدخول والخروج مع تفاصيل حالتك.",
    admissions_empty_title: "لسه مفيش تصاريح مسجلة",
    admissions_empty_desc: "تصاريح الدخول والخروج من المستشفى هتظهر هنا بعد ما يصدرها المستشفى.",
    admissions_entry: "تصريح دخول",
    admissions_exit: "تصريح خروج",
    admissions_status_scheduled: "محدد معاد",
    admissions_status_admitted: "تم الدخول",
    admissions_status_discharged: "تم الخروج",
    admissions_status_cancelled: "ملغى",
    admissions_facility: "المنشأة",
    admissions_department: "القسم",
    admissions_room: "رقم الغرفة",
    admissions_reason: "سبب الدخول",
    admissions_diagnosis: "التشخيص",
    admissions_caseDetails: "تفاصيل الحالة",
    admissions_admissionDate: "تاريخ الدخول",
    admissions_dischargeDate: "تاريخ الخروج",

    // Lab tests
    labs_title: "التحاليل",
    labs_subtitle: "تابع كل تحليل من لحظة أخذ العينة لحد النتيجة.",
    labs_tab_all: "الكل",
    labs_tab_requested: "مطلوبة",
    labs_tab_processing: "جاري التحليل",
    labs_tab_completed: "مكتملة",
    labs_searchPlaceholder: "دور باسم التحليل أو المعمل...",
    labs_empty_title: "لسه مفيش تحاليل",
    labs_empty_desc: "أي تحليل تطلبه إنت أو دكتورك هيظهر هنا بحالته لحظة بلحظة.",
    labs_status_requested: "مطلوب",
    labs_status_processing: "جاري التحليل",
    labs_status_completed: "مكتمل",
    labs_normalRange: "المعدل الطبيعي",
    labs_interpretation: "تفسير النتيجة",
    labs_viewReport: "عرض التقرير",
    labs_requestNew: "اطلب تحليل جديد",

    // Search doctors
    search_title: "دور على دكتور",
    search_subtitle: "فلتر حسب التخصص، المدينة، والتقييم.",
    search_specialtyPlaceholder: "التخصص (مثلاً قلب وأوعية دموية)",
    search_cityPlaceholder: "المدينة",
    search_anyRating: "أي تقييم",
    search_sortBy: "ترتيب حسب",
    search_sort_rating: "الأعلى تقييمًا",
    search_sort_priceAsc: "السعر: من الأقل للأعلى",
    search_sort_priceDesc: "السعر: من الأعلى للأقل",
    search_sort_reviews: "الأكثر تقييمات",
    search_clearFilters: "مسح الفلاتر",
    search_resultsCount: "{count} دكتور موجودين",
    search_loading: "بندور على أحسن الدكاترة ليك...",
    search_empty_title: "مفيش دكاترة مطابقين للفلاتر",
    search_empty_desc: "جرّب تخصص أو مدينة تانية، أو امسح الفلاتر عشان تشوف الكل.",
    search_error: "معرفناش نجيب الدكاترة. اتأكد إن السيرفر شغال.",
    search_popularSpecialties: "تخصصات شائعة",
    doctor_book: "احجز",
    doctor_verified: "موثّق",

    // Doctor profile / booking
    doctor_back: "رجوع للبحث",
    doctor_save: "حفظ",
    doctor_saved: "متحفظ",
    doctor_share: "مشاركة",
    doctor_linkCopied: "اتنسخ لينك البروفايل!",
    doctor_perSession: "جنيه للجلسة",
    doctor_avgSession: "متوسط مدة الجلسة",
    doctor_happyPatients: "مريض راضي",
    doctor_about: "نبذة",
    doctor_aboutFallback: "د. {name} أخصائي {specialty} بخبرة سنين في رعاية المرضى، وحريص إنه يقدم أعلى مستوى من الرعاية الصحية.",
    doctor_qualifications: "المؤهلات والخبرة",
    doctor_qualificationsFallback: "بكالوريوس طب، متخصص في {specialty}",
    doctor_clinics: "عناوين العيادات",
    doctor_bookTitle: "احجز استشارة",
    doctor_typeLabel: "نوع الاستشارة",
    doctor_type_video: "مكالمة فيديو",
    doctor_type_video_desc: "وشك في وشه بالفيديو",
    doctor_type_audio: "مكالمة صوتية",
    doctor_type_audio_desc: "صوت بس",
    doctor_type_text: "شات",
    doctor_type_text_desc: "رسائل مكتوبة",
    doctor_dateLabel: "التاريخ والوقت",
    doctor_pickManually: "اختار بنفسك",
    doctor_nextAvailable: "أقرب المواعيد المتاحة",
    doctor_noSlots: "الدكتور لسه ما حددش مواعيد متاحة — اختار وقت بنفسك وهيأكدهولك.",
    doctor_notesLabel: "ملاحظات (اختياري)",
    doctor_notesPlaceholder: "احكي عن الأعراض أو اللي مضايقك...",
    doctor_submit: "احجز الموعد",
    doctor_submitting: "بيتحجز...",
    doctor_pastDateError: "من فضلك اختار تاريخ ووقت في المستقبل.",
    doctor_noDateError: "من فضلك اختار التاريخ والوقت.",
    doctor_bookedTitle: "تم طلب الموعد!",
    doctor_bookedDesc: "هتوصلك رسالة تأكيد أول ما الدكتور يوافق.",
    doctor_viewDashboard: "شوفه في حسابي",
    doctor_infoEmail: "هيوصلك إيميل تأكيد فيه لينك المكالمة.",
    doctor_trustSecure: "استشارات آمنة ومشفرة",
    doctor_trustCancel: "تقدر تلغي لحد 24 ساعة قبل الموعد",
    doctor_notFound: "معرفناش نلاقي الدكتور ده.",

    // Patient dashboard
    dash_welcome: "أهلاً بيك تاني",
    dash_subtitle: "تابع مواعيدك وسجلاتك الصحية",
    dash_bookAppt: "احجز موعد",
    dash_upcomingAppts: "مواعيد قادمة",
    dash_activePresc: "روشتات فعالة",
    dash_completedVisits: "زيارات مكتملة",
    dash_tabAppointments: "المواعيد",
    dash_tabPrescriptions: "الروشتات",
    dash_loading: "بيتحمل...",
    dash_noAppts_title: "لسه مفيش مواعيد",
    dash_noAppts_desc: "احجز أول استشارة ليك مع دكتور",
    dash_browseDoctors: "تصفح الدكاترة",
    dash_joinCall: "ادخل المكالمة",
    dash_leaveReview: "قيّم الدكتور",
    dash_waitingConfirm: "في انتظار موافقة الدكتور",
    dash_cancelAppt: "إلغاء الموعد",
    dash_cancelConfirm: "تلغي الموعد ده؟ الإجراء ده مينفعش يتراجع فيه.",
    dash_cancelling: "بيتلغي...",
    dash_noPresc_title: "لسه مفيش روشتات",
    dash_noPresc_desc: "الروشتات هتظهر هنا بعد استشارات الدكاترة",
    dash_prescribedOn: "اتكتبت في",
    dash_active: "فعالة",
    dash_noMedicines: "مفيش أدوية مسجلة",
    dash_doctorNotes: "ملاحظات الدكتور",
    dash_orderMedicine: "اطلب الدواء",
    dash_download: "تحميل",
    status_pending: "قيد الانتظار",
    status_confirmed: "مؤكد",
    status_completed: "مكتمل",
    status_cancelled: "ملغى",
    consult_video: "استشارة فيديو",
    consult_audio: "استشارة تليفون",
    consult_text: "استشارة شات",

    // Home — hero
    home_heroTitle1: "رعاية صحية بجودة عالية،",
    home_heroTitle2: "في أي وقت وأي مكان",
    home_heroDesc: "تواصل مع دكاترة موثّقين، واخد استشارة من بيتك وانت مرتاح، وتحكم في صحتك زي ما تحب.",
    home_heroBookBtn: "احجز موعد",
    home_heroHowBtn: "إزاي بيشتغل",
    home_heroEmergencyBtn: "طوارئ؟ دور على مساعدة دلوقتي",
    home_stat1Label: "مريض راضي",
    home_stat2Label: "دكتور متخصص",
    home_stat3Label: "نسبة الرضا",
    home_heroCardTitle: "استشارة فيديو",
    home_heroCardSub: "متاحة 24 ساعة",
    home_heroCardReviews: "4.9/5 (أكتر من 1.2 ألف تقييم)",

    // Home — services
    home_servicesTitle: "حلول صحية متكاملة ليك",
    home_servicesSubtitle: "كل حاجة محتاجها عشان تفضل بصحة كويسة، في مكان واحد",
    service_video_title: "استشارة فيديو",
    service_video_desc: "اتكلم مع دكتور وشك في وشه",
    service_pharmacy_title: "صيدلية أونلاين",
    service_pharmacy_desc: "الدواء يوصلك لحد باب البيت",
    service_labs_title: "تحاليل معملية",
    service_labs_desc: "احجز وتابع نتيجة التحليل",
    service_checkup_title: "كشوفات دورية",
    service_checkup_desc: "باقات وقاية صحية",
    service_specialists_title: "دكاترة متخصصين",
    service_specialists_desc: "دور على أخصائي في تخصصك",
    service_247_title: "متاح 24 ساعة",
    service_247_desc: "احجز في التوقيت اللي يريحك",
    service_secure_title: "آمن وسري",
    service_secure_desc: "بياناتك الصحية محمية",
    service_records_title: "السجلات الصحية",
    service_records_desc: "كل تاريخك الطبي في مكان واحد",
    home_exploreAll: "استكشف كل الخدمات",

    // Home — how it works
    home_stepsTitle: "خطوات بسيطة لصحة أحسن",
    step_account_title: "اعمل حساب",
    step_account_desc: "سجّل في دقايق واكمل بياناتك",
    step_choose_title: "اختار الخدمة",
    step_choose_desc: "اختار الخدمة أو الدكتور اللي محتاجه",
    step_connect_title: "اتواصل مع الدكتور",
    step_connect_desc: "استشير دكتور متخصص وموثّق",
    step_better_title: "اتحسن",
    step_better_desc: "اتبع النصيحة وحافظ على صحتك",
    home_getStarted: "ابدأ دلوقتي",

    // Home — pricing
    home_pricingTitle: "باقات بأسعار تناسب الكل",
    home_pricingSubtitle: "اختار الباقة اللي تناسبك",
    plan_basic_name: "أساسية",
    plan_premium_name: "بريميوم",
    plan_family_name: "عائلية",
    plan_popular: "الأكثر طلبًا",
    plan_perMonth: "/شهريًا",
    plan_choose: "اختار الباقة",
    plan_basic_f1: "5 استشارات شهريًا",
    plan_basic_f2: "دعم عبر الشات",
    plan_basic_f3: "سجل صحي أساسي",
    plan_premium_f1: "استشارات بلا حدود",
    plan_premium_f2: "دعم بأولوية",
    plan_premium_f3: "سجل صحي كامل",
    plan_premium_f4: "خصم 10% على الصيدلية",
    plan_family_f1: "تغطية للعيلة كلها",
    plan_family_f2: "دعم بأولوية",
    plan_family_f3: "سجل صحي كامل",
    plan_family_f4: "خصم 20% على الصيدلية",

    // Home — why choose us
    home_whyTitle: "ليه Wellpoint؟",
    home_whySubtitle: "صحتك هي أولويتنا",
    benefit_experts_title: "دكاترة خبراء",
    benefit_experts_desc: "متخصصين موثّقين وبخبرة كبيرة",
    benefit_secure_title: "آمن وسري",
    benefit_secure_desc: "بياناتك محفوظة ومشفّرة",
    benefit_247_title: "متاح 24 ساعة",
    benefit_247_desc: "استشير في أي وقت وأي مكان",
    benefit_afford_title: "أسعار مناسبة",
    benefit_afford_desc: "رعاية بجودة عالية وسعر معقول",

    // Home — doctors
    home_doctorsTitle: "اتعرف على دكاترتنا المتخصصين",
    home_viewAllDoctors: "شوف كل الدكاترة",
    home_bookNow: "احجز دلوقتي",
    home_noDoctorsYet: "الدكاترة هيظهروا هنا أول ما ينضموا للمنصة.",

    // Home — testimonials
    home_testimonialsTitle: "آراء مرضانا",
    testimonial1_text: "تجربة رائعة! خدت استشارة من دكتور وأنا في البيت. أنصح بيها بجد!",
    testimonial2_text: "خدمة محترفة وسريعة. الدكتور سمعني كويس وديني نصايح مفيدة جدًا.",
    testimonial3_text: "الاستجابة كانت سريعة والاحترافية عالية. وفرلي وقت وفلوس!",

    // Home — CTA
    home_ctaTitle: "خطوة أولى نحو صحة أحسن",
    home_ctaDesc: "احجز استشارة مع واحد من دكاترتنا المتخصصين دلوقتي.",
    home_ctaBtn: "احجز موعد",

    // Emergency
    emergency_navLabel: "طوارئ",
    emergency_title: "مساعدة في الطوارئ",
    emergency_subtitle: "شارك موقعك عشان نلاقيلك أقرب مستشفى ودكاترة، مع اتجاهات الطريق.",
    emergency_locate_cta: "استخدم موقعي الحالي",
    emergency_locating: "بنحدد موقعك...",
    emergency_searchingHospitals: "بندور على أقرب مستشفيات...",
    emergency_searchingDoctors: "بندور على أقرب دكاترة...",
    emergency_routing: "بنحسب الطريق...",
    emergency_deniedTitle: "محتاجين إذن الوصول لموقعك",
    emergency_deniedDesc: "من فضلك اسمح بالوصول لموقعك من المتصفح عشان نلاقيلك أقرب مساعدة.",
    emergency_retry: "حاول تاني",
    emergency_nearestHospital: "أقرب مستشفى",
    emergency_otherHospitals: "مستشفيات تانية قريبة",
    emergency_nearestDoctors: "أقرب دكاترة",
    emergency_distanceAway: "على بعد {distance} كم",
    emergency_etaDriving: "حوالي {minutes} دقيقة بالعربية",
    emergency_noHospitals: "مفيش مستشفيات قريبة. جرّب توسّع نطاق البحث أو اتأكد من النت.",
    emergency_noDoctors: "لسه مفيش دكاترة مسجلين قريبين منك.",
    emergency_callHospital: "اتصل بالمستشفى",
    emergency_getDirections: "افتحه في الخرايط",
    emergency_viewProfile: "شوف البروفايل",
    emergency_yourLocation: "موقعك",
    emergency_disclaimer: "لو في حالة طوارئ بتهدد الحياة، اتصل فورًا برقم الطوارئ المحلي عندك. الأداة دي بس بتساعدك تلاقي رعاية قريبة بسرعة، ومش بديل عن خدمات الطوارئ.",
    emergency_mapUnavailable: "معرفناش نحمّل الخريطة. اتأكد من اتصالك بالنت.",
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  useEffect(() => {
    localStorage.setItem("lang", lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = translations[lang].dir;
  }, [lang]);

  const t = (key, vars) => {
    let str = translations[lang]?.[key] ?? translations.en[key] ?? key;
    if (vars) {
      Object.entries(vars).forEach(([k, v]) => {
        str = str.replace(new RegExp(`\\{${k}\\}`, "g"), v);
      });
    }
    return str;
  };
  const toggleLang = () => setLang((l) => (l === "en" ? "ar" : "en"));

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang, dir: translations[lang].dir }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
